services:
  node:
    image: node:20-alpine3.16
    expose:
      - "3000"
      - "3001"
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/code
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5
